# 2017/12/18
# William Whitacre
# Radix 7 Table-3 Generator

import haas, system, sequtils, math, times

var haas_add3_tab: array[0..6, array[0..6, array[0..6, range[0..6]]]]
var haas_carry3_tab: array[0..6, array[0..6, array[0..6, range[0..6]]]]

proc haas_add3_tabulate[T: SomeInteger](n, m, o: T): void =
  haas_add3_tab[n][m][o] = haas_add3_digits(n, m, o)
  haas_carry3_tab[n][m][o] = haas_addc3_digits(n, m, o)

proc haas_print3(name: string, t: auto) =
  echo "const ", name, " = ["
  for i in 0..6:
    echo "  ["
    for j in 0..6:
      stdout.write "    ["
      for k in 0..6:
        stdout.write t[i][j][k]
        if k < 6: stdout.write ", "
      stdout.write("]" & (if j < 6: ",\n" else: "\n"))
    stdout.write("  ]" & (if i < 6: ",\n" else: "\n"))
  echo "]"

for i in 0..6:
  for j in 0..6:
    for k in 0..6:
      haas_add3_tabulate(i, j, k)

echo "# Autogenerated by bootstrap, detail/ag/tab3.nim"
echo "# ", get_date_str(), "   ", get_clock_str()
echo ""

haas_print3("haas_add3_table*", haas_add3_tab)
echo ""

haas_print3("haas_carry3_table*", haas_carry3_tab)
echo ""

